examples: fix get_connectivity_monitor example
aristanetworks/cloudvision-python pull request #28
Opened 2024-10-31 14:48 UTC by guillaumeVilar

When using the example in examples/resources/connectivitymonitor, I got the following error: 

```
$ python3 get_connectivity_monitor.py --apiserver <MY-CVP-IP>:443 --token token.txt --cert cvp.crt --device <DEVICE-SN>
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1730382229.854067 1242722 ssl_credentials.cc:149] Check failed: pem_key_cert_pair->private_key != nullptr ((null) vs. (null)) 
*** Check failure stack trace: ***
Aborted (core dumped)
```
This error comes from the GRPCClient, and we are using that class only to get the mapping between S/N to hostname. 

In this PR, I replaced the GRPCClient with inventory resources to get the inventory data, which makes more sense from my point of view as we are already using the resources API to get connectivity monitor info.

2024-11-01 13:01 UTC, cianmcgrath requested changes
Some linting failures in your change, looks good once addressed

2024-11-01 13:01 UTC, cianmcgrath commented on examples/resources/connectivitymonitor/get_connectivity_monitor.py
> +     # make the GetAll request and loop over the streamed responses
./get_connectivity_monitor.py:35:6: E114 indentation is not a multiple of four (comment)

2024-11-01 13:01 UTC, cianmcgrath commented on examples/resources/connectivitymonitor/get_connectivity_monitor.py
> +
./get_connectivity_monitor.py:40:1: E302 expected 2 blank lines, found 1

2024-11-05 16:11 UTC, cianmcgrath approved these changes

2024-11-05 16:12 UTC, guillaumeVilar commented
Thanks for the review - I did the following in my commits: 
* Fix the linting issues you pointed out
* The output is now a list of dict (for easier integration with 3rd party app)
*  The example failed when no device was provided. 
With the changes, output for one device:
```
$ python3 examples/resources/connectivitymonitor/get_connectivity_monitor.py --apiserver <IP-CVP>:443 --token token.txt --cert cvp.crt --device <S-N>
[{'hostname': 'PS-SWITCH', 'serial_number': '<S-N>', 'vrf': 'default', 'interface': 'default', 'host': 'host1', 'ip_addr': '192.168.10.2', 'description': '', 'http_response': 0.0, 'jitter': 0.02500000037252903, 'latency': 0.21799999475479126, 'packet_loss': 0}, {'hostname': 'PS-SWITCH', 'serial_number': '<S-N>', 'vrf': 'MGMT', 'interface': 'default', 'host': 'internet', 'ip_addr': '8.8.8.8', 'description': 'internet access', 'http_response': 0.0, 'jitter': 0.06400000303983688, 'latency': 1.2960000038146973, 'packet_loss': 0}]
```

Output for all the devices (so without the `--device` argument):
```
$ python3 examples/resources/connectivitymonitor/get_connectivity_monitor.py --apiserver <IP-CVP>:443 --token token.txt --cert cvp.crt 
[{'hostname': 'PS-SWITCH-1', 'serial_number': '<S-N>', 'vrf': 'default', 'interface': 'default', 'host': 'host1', 'ip_addr': '192.168.10.2', 'description': '', 'http_response': 0.0, 'jitter': 0.017999999225139618, 'latency': 0.22100000083446503, 'packet_loss': 0}, {'hostname': 'PS-SWITCH-2', 'serial_number': '<S-N>', 'vrf': 'mgmt', 'interface': 'default', 'host': 'internet_mgmt', 'ip_addr': '8.8.8.8', 'description': 'internet access mgmt', 'http_response': 0.0, 'jitter': 0.07599999755620956, 'latency': 1.2899999618530273, 'packet_loss': 0}, {'hostname': 'PS-SWITCH-3', 'serial_number': '<S-N>', 'vrf': 'MGMT', 'interface': 'default', 'host': 'internet', 'ip_addr': '8.8.8.8', 'description': 'internet access', 'http_response': 0.0, 'jitter': 0.07699999958276749, 'latency': 1.3480000495910645, 'packet_loss': 0}]
```

2024-11-05 16:13 UTC, merged

2024-11-05 16:13 UTC, cianmcgrath commented
Thanks Guillaume 👍